### ISSUE TITLE
Simulator always shows rooted

### ISSUE THREAD

**Issue by szh** [trykovyura/cordova-plugin-root-detection#4]
On the Android Simulator (tested 7.0 and 5.0), the plugin always thinks the system is rooted. This makes it impossible to test my app on the simulator unless I create a separate build which doesn't contain the plugin.

**Comment by trykovyura** [comment]
That's true. Because of checkFilePath. You free to fork and change this method. Or other debug options in you app. Or try with genymotion emulator.
